name       : haskell-clock
version    : '0.8'
release    : 3
source     :
    - https://hackage.haskell.org/package/clock-0.8/clock-0.8.tar.gz : 08a35c5294009040f1e5eb721a21b60df7af6584092bb3d376ab1b2e57e26914
license    : BSD-3-Clause
component  : programming.haskell
summary    : A package for convenient access to high-resolution clock and timer functions of different operating systems via a unified API.
description: |
    A package for convenient access to high-resolution clock and timer functions of different operating systems via a unified API.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
