name       : haskell-clock
version    : 0.7.2
release    : 2
source     :
    - http://hackage.haskell.org/package/clock-0.7.2/clock-0.7.2.tar.gz : 886601978898d3a91412fef895e864576a7125d661e1f8abc49a2a08840e691f
license    : BSD-3-Clause
component  : programming.haskell
summary    : A package for convenient access to high-resolution clock and timer functions
    of different operating systems via a unified API.
description: |
    A package for convenient access to high-resolution clock and timer functions of different operating systems via a unified API.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
